apiVersion: v1
kind: Secret
metadata:
  name: manejo-finanzas-secrets
type: Opaque
stringData:
  .env: |
    DB_HOST=TODO
    DB_NAME=manejo_finanzas
    DB_USER=root
    DB_PASWORD=password
    DB_DRIVER=mysql
    DB_CHARSET=utf8mb4